## 運動量

運動方程式はそれ単体でかなりの現象を説明するものですが，世の中にはあまりにも多くの粒子が複雑に互いに力を及ぼし合っているので，解析し切ることができることが難しいことが多いです．

そんな中で，前章でも述べた通り，多粒子を考える方法はあり，これからはその方法の一つを考えることにしましょう．

まず，言葉の定義として，運動量について紹介します．

::: {.Dbox data-latex="{定義}"}

とある物体が質量 $m$ ，速度 $\bm{v}$ を持っている時，その物体の運動量 $\symbfit{p}$ を次のように定義する．

$$\symbfit{p}=m\symbfit{v}$$

:::

つまり，運動方程式は次のようにかけます．
$$\dot{\symbfit{p}}=\symbfit{F}$$
多粒子系について考えましょう．前章と同様，とある場所に $n$ 個の粒子があり，それらが互いに力を及ぼしながら，外からも力を受けているとしましょう．その時， $i$ 番目の粒子の運動方程式は
$$
\begin{aligned}
\dot{\symbfit{p}_i} = \sum_j \symbfit{F}_{ij} +  \symbfit{F}_{i\text{out}}
\end{aligned}
$$
ここで， $\symbfit{F}_{ij}$ は $j$ 番目の粒子が $i$ 番目の粒子に及ぼす力であり， $\symbfit{F}_{i\text{out}}$ は $i$ 番目の粒子が受ける外力です．この式を全ての $i$ について足し合わせることによって，
$$
\begin{aligned}
\sum_i \dot{\symbfit{p}_i} &= \sum_i\sum_j \symbfit{F}_{ij} +  \sum_i\symbfit{F}_{i\text{out}}
\end{aligned}
$$
作用反作用の法則によって， $\sum_i\sum_j \symbfit{F}_{ij}$ となるので，
$$
\begin{aligned}
\sum_i \dot{\symbfit{p}_i} &= \sum_i\symbfit{F}_{i\text{out}}
\end{aligned}
$$
ここで外力がないとすると，
$$
\begin{aligned}
\sum_i \dot{\symbfit{p}_i} &= \symbfit{0}\\
\dv{t}\sum_i \symbfit{p}_i &= \symbfit{0}\\
\sum_i \symbfit{p}_i &= \textbf{Const.}=M_{\text{tot}}\dot{\symbfit{r}}_{\text{G}}
\end{aligned}
$$
このような結果が得られるわけです．このようにある値が定数であり続けることを，値が保存していると呼ばれます．また，全運動量の合計は，全質量と重心速度の積によって表すことができることもわかりました．以上をまとめると，

::: {.Tbox data-latex="{定理}"}

外力の働かない系では，全運動量が保存する．また，系の全運動量 $\symbfit{P}$ は

$$\symbfit{P}=M_{\text{tot}}\symbfit{v}_{\text{G}} $$

で表すことができる．
:::

ここで，重心の定義を考えた時，
$$
\begin{aligned}
\sum_i m_i (\symbfit{r}_i-\symbfit{r}_\text{G})=\sum_i m_i \symbfit{r}_{i\text{G}}=\symbfit{P}_{\text{in}}=\symbfit{0}
\end{aligned}
$$

ここで， $\symbfit{P}_{\text{in}}$ 重心から見た物体内部の全運動量ということで，内部運動量と呼ばれています．つまり，

::: {.Tbox data-latex="{定理}"} 定理

任意の系を，重心を原点とする座標系で見れば，全運動量は $\symbfit{0}$ となる．別の言い方をすれば，内部運動量は常に $\symbfit{0}$ となる．

:::

::: {.Rbox data-latex="{例題}"}

宇宙の外力の及ばない場所に星がひとつあった．その星の中で何らかの現象が起き，その結果，二つの星が出来上がり，片方は質量 $m_1$ で速度 $\symbfit{v_1}$ だった．もう片方の質量が $m_2$ だった時の速度を求めよ．

:::

::: {.Abox data-latex="{解答}"}

$$m_1\symbfit{v_1}+m_2\symbfit{v_2}=\symbfit{0}$$
$$\symbfit{v_2}=-\frac{m_1}{m_2}\symbfit{v_1}$$

:::
