project:
  type: book
  output-dir: docs

book:
  title: "Physics Text"
  author: "Serika Yuzuki, Akina"
  date: "3/2/2023"
  chapters:
    - index.qmd
    - source/intro.qmd
    - source/velocity.qmd
    - source/newton-mechanics.qmd
    - source/energy.qmd
    - source/database.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



