# Preface {.unnumbered}

この本は物理初習者のためのものである．至らぬことも多いかも知れないが，アップデートによって更新していくつもりです．

## この本を書く際の気持ち

この本を書いた際に２通りの気持ちを込めております．それは，一流大学を目指す皆さんがこの本を説き上げた暁には，

１．物理という学問の楽しさを知っていただき，

２．皆さんの物理的素養が大学やその以降の人生でも役に立っていただく．

ことであります．

## この本の対象とする人

また，この本の読者の想定は，

１．ある程度高校物理を一通り教科書で読み切った程度の受験生．

２．高校数学を逸脱しない程度に高度な数学を使うことに対して躊躇いのない，チャレンジ精神あふれる受験生．

３．東大・京大・東工大など最難関大学の入試を凌駕し，物理オリンピックにもたじろぐことのない実力をつけたい受験生．

であります．だからと言ってこの本では物理学における原理原則を省いたものであるわけではなく，むしろそれを非常に重視した作りになっているので，中学校で理科科目に十分勉強時間を割いた生徒や，数学的素養のある生徒であれば，初見でも読み切れるように工夫してあります．

もしもこの本を読んで，ついていけない，難しすぎると感じるのであれば，教科書，もしくはそれと同程度の記述がなされている市販の参考書を一通り読んだのちに取り組むことをお勧めします．

## この本の特徴

未来の知的なエリートとして活躍するであろう諸君にとって，無理のない程度の発展的内容を含めていることこそ，本書にしかない特徴だと言えます．

受験勉強の際には，皆さんが手にするであろう，いたずらに詳細で”超親切な”参考書の暗記では通用しないような，解答に高度な物理学の基本への理解と，卓越した発想力を要するような問題が，有名各大学から出題されるようになりました．受験業界の規模拡大により，様々な入試問題のパターンを全てカバーしたような所謂”網羅系”の参考書が安価に誰の手にも渡るようになり，教科書の内容に従った素直な問題では，受験生が”理解”して問題を解いているのか，”暗記”して問題を解いているのかを判定することが難しくなり，故に思考力を問うような，斬新な装置や複雑な設問が頻出するようになったように思われます．

この本が，そのような問題への，パターン暗記ではない，決定的な対策書として働けば嬉しい限りであります．

## この本の使い方

この本能構成としては，

１．まず，最初に基本的な概念の解説を明快に提示し，

２．次に，その概念を理解するための問題を列挙する

というふうになっています．

数学や物理の勉強とはいわば将棋の勉強と似たところがあります．

将棋の名人となるには数年，数十年に渡る勉強が必要ですが，肝心の将棋のルール自体は非常に簡明であり，初心者に対しても１０分程度あれば説明し切ることができます．それは数学や物理の勉強にも言えて，数学や物理の各分野についても，”ルール”となる定義，原理は非常にシンプルであり，理解するに時間は要りません．

しかしながら，多くの受験生は”ルール”となる定義，原理についても，理解が及ばず，そこで躓き続けていることが多いのです．その理由は，多くの受験生が，将棋で言うところの，将棋のコマの動かし方の前に，飛車が取られないように動くべきだという戦略（経験則）について教わるからです．

確かに飛車を取られることは避けるべかもしれません．ですが，飛車を取られたからといって対局に負けるわけではないし，飛車を差し出すことが必要な局面も存在します．

実際にこのような状況が，数学においてはどのようになるのかを話してみます．例えば，自然数の足し算を教える際に，上の述べるところのやり方を説明すると，

\begin{align*}
1+1&=2\\
12+37&=49\\
423+109&=532\\
9861+3685&=13546
\end{align*}

というように，いろいろな足し算の問題と結果を経験則で覚えることに対応します．週末に出される内容が予告された小テストに間に合わせるためならば，この勉強法は非常に理にかなったものになりますが，これでは年度末のテストには対応できそうにありません．

ここで必要になるのは，足し算とは何か，その結果習得できる組み立て算についての知識なのです．

故に，この本の各章の最初には，将棋のルールたる，物理学の基本原理の説明を入れてあります．内容自体は簡潔に思われるかもしれませんが，この理解は決しておろそかにしてはいけません．他人に説明できるようになるまで勉強しておきましょう．

次に，経験則も非常に重要になってきます．確かに将棋のルールは簡単ですが，名人に誰しもがなれるわけではない理由がここにあるのです．コマの動かし方はわかったが，どう動かせばいいのかわからない，この状況は避けなくてはなりません．特にダニング＝クルーガー効果とは，この原理原則だけを聞き齧った状況に起きるものではないでしょうか．

故に，この本にはかなりたくさんの問題を入れることになりました．皆さんには是非とも物理の名人になって欲しいからです．

また，ある程度学習を進めた時々に，題材が複雑な問題の章も挟みましたので，是非とも腕試し，腕磨きにやって頂ければ嬉しい限りです．

