これまでの章で皆さんが学んだ内容は運動学と呼ばれますが、運動学は物体の動き方（速度と加速度）を説明する学問です。

これから皆さんが学ぶことになる力学は、力が物体や系の運動にどのように影響するかを研究する学問となります。力学の基礎は、アイザック・ニュートンによって法則としてまとめ上げられました。この法則は非常にシンプルなのにも関わらず、自然界をかなりの精度と範囲で記述することができています。また，この法則は、地球のみならず，惑星の動きなど，宇宙空間の状況に適用されるという点で、普遍的な法則でもあります。

ニュートンの法則の発見は、ルネサンスから近代へと時代を変え，２０世紀初頭の現代物理学の登場までこの宇宙の須くを記述し切れるものだと考えられました．ただし，現代でも $10^{-8}$ m以下の世界を除けば，ニュートンの法則はかなりの精度をもって自然を記述することができます．また，逆にこの制約がニュートン力学の領域を定義することにもなります。20世紀初頭、アルベルト・アインシュタインは相対性理論を提唱し、他の多くの科学者と共に量子力学を発展させていきました。ゆくゆくはその領域にも話を進めるつもりでいますが，今の所はニュートン力学の理解を進めていきましょう．

力学とは、物体や系の動きを引き起こす力についての学問です。このことを理解するためには、力の定義が必要です。力の直感的な定義ですが，まず手始めには「押す」や「引く」といったものとして考えてみましょう．台車を手のひらで押すとその感触がして，台車が動き始める．その感触を定義とするわけです．ここで，「押す」や「引く」には，向きと大きさが存在するわけで，ゆえにこれを記述するにはベクトルを使うことになります．

もう少しこの直感に力の定義に従って自然界を観察してみることにしましょう．まず，私たちが実際に感じられる力のうちの一つが，重力であることは言うまでもないでしょう．では，重力の持つ特徴とはなんだったのでしょうか．ものを動かすこと？　では，ものを動かすとはどう言う意味でしょうか．物体の座標を変化させること？　では，それはどのようにでしょうか．

落下運動を深く観察してやると，物体に一定の速度を持たせる，と言うのではなく，物体に一定の割合で速度を与えているとわかります．これは実験的事実であり，同時に前の章で私たちはすでに重力加速度として実際に問題を解いていたりもしました．

では，この洞察を次のようにまとめることはできないでしょうか．

::: {.callout-note icon=false}

## ニュートンの第２法則（半分）

物体に力が働く時，その物体は加速度を持つ．
:::

では，この関係性はどのようになっているのでしょうか．つまり物体に働く力を $\boldsymbol{F}$ ，物体の位置を $\boldsymbol{r}$ として，
\begin{align*}
    \boldsymbol{F} = f(\ddot{\boldsymbol{r}})
\end{align*}
と言う関数 $f$ が存在すると言うことである．この関数の形を知ることができれば，私たちは力学の根本の大きな部分を理解することになるのですが，これについては偉大なる先人たちが導き出してくれました．なんとこの関数は一次関数だったのです．そして，その比例係数の逆数を，質量と呼ぶようになりました．

::: {.callout-note icon=false}

## ニュートンの第２法則(運動方程式)

物体の質量を $m$ ，物体の位置を $\boldsymbol{r}$ ，物体に働く力を $\boldsymbol{F}$ とした時，次の式が成り立つ．

$$\ddot{\boldsymbol{r}}=\frac{1}{m}\boldsymbol{F}$$
:::

ここで，$$m\ddot{\boldsymbol{r}}=\boldsymbol{F},\;\boldsymbol{F}=m\ddot{\boldsymbol{r}}$$ どちらがいいのかとか言う問題には立ち入らないことにします．式の順番に意義があると思われる方は自らの信念に従っていただければ嬉しいです．筆者の考えるところでは，とある視点に基づいて考えるよりかは，色々な視点で持って数式は見るべきであり，数式に意味を持たせるべきと言う意見よりも，数式に意味を見出すべきだと言う意見を採用したいと思っています．

では，これから推察できる簡単な事実を考えましょう．すなわち，力の働いていない物体はどのような運動をするのか，です．これは非常に簡単で $m\ddot{\boldsymbol{r}}=\boldsymbol{0},\;\dot{\boldsymbol{r}}=(\text{一定})$ と言う非常にシンプルな結果となるわけです．つまり，次のようにまとめられるわけです．

::: {.callout-note icon=false}

## ニュートンの第1法則(慣性の法則)

力の働いていない物体は，常にその速度を保つ．

:::

そして最後に，力の持つ性質を述べようと思います．それは，作用反作用の法則と呼ばれるものです．

::: {.callout-note icon=false}

## ニュートンの第３法則(作用反作用の法則)

物体に働く力は，常にある２つの物体の間で及ぼしあうように働く．物体Aが物体Bに及ぼす力を $\boldsymbol{F_{BA}}$ ，物体Bが物体Aに及ぼす力を $\boldsymbol{F_{AB}}$ とした時，次の式が成り立つ．
$$\boldsymbol{F_{BA}}+\boldsymbol{F_{AB}}=\boldsymbol{0}$$

:::

つまり，地球があなたを引っ張っているのと同じくらい，あなたは地球を引っ張っているのです．非常に非直感的な法則です．同時に，壁があなたに押されていると同じくらい，あなたは壁に押されるというのも同じ作用反作用の法則です．こちらは直感的ですね．

これらの法則を実際にどのようにして問題に応用するべきでしょうか．これからは実際に問題を解いていくことによって，それらを明らかにしていこうと思います．
