# 位置，速度，加速度

この章では主に速度とか速度についてお話しさせていただきます．

まず，物理の話を始める際において，物理は何かということを明らかにしなければなりません．ところが物理とは何かという問題はあまりに大雑把で，人によってその定義が変わるものだし，専門とする分野によっても大きく姿を変えることでしょう．ですが，それらを全てまとめ上げ，最大公約数的な解答を一つ提示できるとすれば，私たちの身の回りで起きている，現象について語る学問だということになるのではないかと思います．

例えば，皆さんがこの本をパソコン越しでみているとします．その時，パソコンに映る表示映像というのも何らかの現象でしょう．ではその現象を観察し，何か語れるものがあるのかと考えてみましょう．例えば，「あ」という文字と「あ」という文字は全くもって同じ形をしているという法則が見つけられるかもしれません．マウスホイールを回すとテキストが流れていくという法則も見えてくるでしょう．

ところが現象とざっくり言ってしまっては，どの現象をどの角度から見ることになるかがはっきりしてきません．では，私たちがこれから学ぶ物理学の，ひとまず注視することとなる現象を考えることから始めましょう．その現象とは，動く物体です．

ここでは話がわかりやすくイメージできるように，とあるパチンコ玉を考えてみましょう．そのパチンコ玉は机の上に置かれていて，手で弾いてやると机の上をまっすぐ転がっていき，やがて机の淵から落ちて地面と衝突し，数度バウンスしたのちに床で止まりました．

さて，この現象を語るのに今は日本語という言葉を使いましたが，これでパチンコ玉の運動の仔細は語り尽くされたのでしょうか．弾き飛ばされたパチンコ玉がどれくらい早く動き，机に対してどんな角度で転がって，机の淵までどれくらいの時間で辿り着き，バウンスによってどれだけの高さに跳ね上がり，どの場所でその動きを止めたのか．少なくともこれらの情報がなければ，現象を語られた人が同一の現象を想定することは不可能でしょう．また，これらの情報を渡されたところで，全く同じ現象を想定するのも難しいに違いありません．そしてその再現度こそが，現象を語り尽くすことの根幹なのではないでしょうか．

では，どうすれば，パチンコ玉の運動を語り尽くせるのでしょうか．その時に使われるのが，数学の力なのです．

パチンコ玉の中心点の座標 $\boldsymbol{r}$ を，時間 $t$ ごとに追っていって，その全ての時間に対して解析を行い，時間の関数となる $\boldsymbol{r}(t)$ を書き上げれば，上に書かれたすべての疑問に対して回答することができ，さらには現象を語り尽くすことができるのではないでしょうか．もっと具体的に言えば，パチンコ玉の回転なども考慮すべきでしょうが，今の所，それは無視することにします．

では，今，私たちはパチンコ玉の運動を語り尽くす手段を知りました．では，その運動の様相をどのようにして解析するのかを考える段階に入りましょう．確かに，パチンコ玉は $\boldsymbol{r}(t)$ に従って動いていますが，我々の直感として「動いている」と感じることのできる指標である「速さ」が必要になるでしょう．動いているか，動いていないかの判別にも使えるし，動いている様相の説明にも使えるでしょう．

また，物理学という学問の性質上，古の巨人が築き上げた知識を引き継ぐことが大いにありますが，ニュートンの語るところによれば，物体の運動において大きな役割を持つ指標が加速度であるので，それも合わせて定義していくことにします．

::: {.callout-note icon=false}

## 定義

とある物体の時刻 $t$ における位置ベクトルを $\boldsymbol{r}(t)$ とした時、

その物体の速度を 
$$\boldsymbol{v}(t)=\frac{d\boldsymbol{r}}{dt}=\dot{\boldsymbol{r}}$$

加速度を 
$$\boldsymbol{a}(t)=\frac{d^2\boldsymbol{r}}{dt^2}=\ddot{\boldsymbol{r}}=\dot{\boldsymbol{v}}$$

 と定義する。また、 
 $$\boldsymbol{r}(0),\boldsymbol{v}(0)$$
 をそれぞれ初期位置、初速度と呼ぶ。

:::
