## 速度及び加速度

パチンコ玉の中心点の座標 $\symbfit{r}$ を，時間 $t$ ごとに追っていって，その全ての時間に対して解析を行い，時間の関数となる $\symbfit{r}(t)$ を書き上げれば，上に書かれたすべての疑問に対して回答することができ，さらには現象を語り尽くすことができるのではないでしょうか．もっと具体的に言えば，パチンコ玉の回転なども考慮すべきでしょうが，今の所，それは無視することにします．

では，今，私たちはパチンコ玉の運動を語り尽くす手段を知りました．では，その運動の様相をどのようにして解析するのかを考える段階に入りましょう．確かに，パチンコ玉は $\symbfit{r}(t)$ に従って動いていますが，我々の直感として「動いている」と感じることのできる指標である「速さ」が必要になるでしょう．動いているか，動いていないかの判別にも使えるし，動いている様相の説明にも使えるでしょう．

また，物理学という学問の性質上，古の巨人が築き上げた知識を引き継ぐことが大いにありますが，ニュートンの語るところによれば，物体の運動において大きな役割を持つ指標が加速度であるので，それも合わせて定義していくことにします．

::: {.Dbox data-latex="{定義}"}

とある物体の時刻 $t$ における位置ベクトルを $\symbfit{r}(t)$ とした時、

その物体の速度を 
$$\symbfit{v}(t)=\frac{d\symbfit{r}}{dt}=\dot{\symbfit{r}}$$

加速度を 
$$\symbfit{a}(t)=\frac{d^2\symbfit{r}}{dt^2}=\ddot{\symbfit{r}}=\dot{\symbfit{v}}$$

 と定義する。また、 
 $$\symbfit{r}(0),\symbfit{v}(0)$$
 をそれぞれ初期位置、初速度と呼び，速度の絶対値を速さと呼ぶ．

:::

速度とは，わずかな時間における時間あたりの位置の変化です．つまり，そのわずかな時間をかけてやることによって，わずかな時間に起きた位置の変化を求めることができ，さらに，そのわずかな時間に起きた位置の変化を全て足し合わせることによって，位置を求めることができるのです．

ここで， $t=0$ から $t=T$ までの時間を $n$ 個に区切り，その一区切りの時間の長さを $\Delta t$ ， $i$ 区切り目の時刻を $t_i$ としてやれば，

$$\symbfit{r}(t)\approx\sum_{i=0}^n \symbfit{v}(t_i)\Delta t$$

とすることができ，極限をとってあげることによって

$$\symbfit{r}(t)= \lim_{\Delta t \to 0}\sum_{i=0}^n \symbfit{v}(t_i)\Delta t=\int \symbfit{v}(t_i)\dd t$$

となるわけです．同様の話が加速度についても言えます．では，これからは実際に例題を用いて，今までの知識を深めていきましょう．

::: {.Rbox data-latex="{例題}"}

$x$ 方向への一次元で，速度が一定 $v$ の物体の運動を考える．最初物体は $x=x_0$ にあったとして，時刻が $t=T$ になった時の位置を求めよ．

:::

::: {.Abox data-latex="{解答}"}

まず， $x=x_0$ から $t=T$ だけ経った時に物体がどれだけ動いたか考えると

$$\int_0^T v \dd t=vT$$

なので， $x_0+vT$ が答えになる．

次に別の方法を考えると，

$$x=\int v \dd t = vt+C$$

であるので，初期条件の $t=0,\; x=x_0$ を代入すると

$$x = vt + x_0$$

ここで，積分が定積分ではなく，不定積分であることに注目せよ．定積分でない理由は，この場合， $x$ を求めるのに，微分の逆演算をしているに過ぎず，ある定まった区間での積分として考えていない．

:::

次の問題では，一次元の等加速度運動を全てまとめているものになります．

::: {.Rbox data-latex="{例題}"}

$x$ 方向への一次元で，加速度が一定 $a$ の物体の運動を考える．時刻 $t=t_0$ 物体は $x=x_0,\; v=v_0$ だったとして，時刻が $t$ になった時の位置を求めよ．

:::

::: {.Abox data-latex="{解答}"}

前の問題の結果を使えば，

$$v=v_0+\int_{t_0}^{t}v\dd t = v_0 + a(t-t_0)$$

この解答は $(t-t_o)$ を一塊としてみて，先の問題の $T$ のように扱っている．塊として考えればこれからの問題も比較的楽に解決される．ここでは $T=t-t_0$ とすれば，

$$v=v_0 + aT$$

$$x-x_0=\int_{0}^{T}v\dd t =\frac{1}{2}aT^2+v_0T$$

$$x = \frac{1}{2}aT^2+v_0T + x_0$$

このように扱うことができるわけだが，読者が問題解決の際には $T$ をわざわざ定義しなくとも，塊のまま見てあげることによって，

$$x = \frac{1}{2}a(t-t_0)^2+v_0(t-t_0) + x_0$$

としてあげれば良い．

:::
