## 前説

この章では物理の世界に入る前に知っておかなければならないことを説明します．

物理学を始める際にして、初学者の方にはどうしてもある程度の数学の素養が求められます。物理学の発展と数学は決して離すことのできない物であり、例えばみなさんがこれかあら学ぶ力学の分野は、微分と積分の関係性を発見し、それを基礎にしてニュートンが発展させた分野です。

ですがそこが最大の関門として高校生の皆様には立ちはだかることになると思います．ベクトルも微分も積分も，なんなら三角関数もまともにやったことがないのに，いきなり全部を使いこなせることを要求されてしまうからです．

なので，この章では読者が高校2年生の途中くらいから読み始めているものだと想定して，数学について少しずつ勉強を進めながら，物理を始められるところまでやっていこうと思います．関数の定義や三角関数については流石にもう慣れてきたのではないかという時期ですね．もしもまだそこがあやふやであるのならば，まずは数学の教科書をある程度進ませてからこの本を読んでいただければ幸いと思っています．

また，初学者の方でもある程度は学びを進められるように配慮はしてありますが，もしもこの本の記述が難しい，ついていけないように感じられるのであれば，高等学校の教科書や市販の参考書などとともに読み進めていただくと良いかもしれません．

ですが，すでに一通り数学をやっている方ならば，この章を飛ばしていただいても構いません．そのための指標として，まずはこの章におけるゴールを一通り書いておきます．次の表に載せてあることを理解できるようになれば，ひとまずこの章は学び終えたという判定で考えてもらって構いません．

::: {.Tbox data-latex="{数学の公式}"}

|||
|-|---|
|微分の定義| $$\dv{x} f(x)=\lim_{\Delta x\rightarrow 0}\frac{f(x+\Delta x)-f(x)}{\Delta x}$$ |
|積の微分法| $$\dv{x}\{f(x)g(x)\}=f'(x)g(x)+f(x)g'(x)$$ |
|商の微分法| $$\dv{x}\{\frac{f(x)}{g(x)}\}=\frac{f'(x)g(x)-f(x)g'(x)}{\{g(x)\}^2}$$|
|冪函数の微分法| $$\dv{x}x^r=rx^{r-1}$$ |

: {tbl-colwidths="[25,75]"}

:::

では，始めましょう．
