## 微分積分学の基本定理

1.7でみたように，面積の値を定積分として定めました．ここで，$x$を変数とした
$$\displaystyle\int_{a}^{x}f(t)dt$$
は，$x$の関数だと考えることができます．これを$f(x)$の不定積分と呼びます．

よく言われるように，微分と積分というのは互いに逆演算になっています．しかし，先の積分の項を読んだ方は，定積分の定義のどこにも微分が登場していない，ということにお気づきだと思います．実は微分と積分はそれぞれ独立して成立した分野で，後になって実は互いに関わりあっているということが分かったのです．

さて，次の定理は微分積分学の基本定理と呼ばれており，微分と積分を繋ぐ重要な事実です．

::: {.Tbox data-latex="{定理}"}


$$\displaystyle\frac{d}{dx}\displaystyle\int_{a}^{x}f(t)dt=f(x)$$

:::

これは，積分したものを微分すると元に戻る，ということを述べている定理です．この事実を使えば，わざわざ定義からいちいち積分をしなくても，「微分すると $f(x)$ になる関数」（これを原始関数といいます）を見つけられれば $f(x)$ の積分が求められる，ということになります．今後， $f(x)$ の不定積分は $\displaystyle\int_{}^{}f(x)dx$ とかくことにします．

::: {.Rbox data-latex="{例題}"}
次の不定積分を求めよ．
$$\displaystyle\int_{}^{}x\ dx $$

:::

::: {.Abox data-latex="{解答}"}

微分の知識を思い出せば， $\displaystyle\frac{1}{2}x^2$ の微分が $x$ になることはすぐにわかる．しかし，同様に $\displaystyle\frac{1}{2}x^2+1$ も，$\displaystyle\frac{1}{2}x^2-99$ も，
$\displaystyle\frac{1}{2}x^2+\pi$ も， $\displaystyle\frac{1}{2}x^2$ に定数を足したものはすべて微分すれば$x$になる．これらをまとめて， $\displaystyle\frac{1}{2}x^2+C$とかき，$C$を積分定数という．もとの例題に対する答えは， 
$$\displaystyle\int_{}^{}x\ dx =\displaystyle\frac{1}{2}x^2+C~\mbox{($C$は積分定数)}$$
である．

:::

上の例題のように，不定積分の結果には積分定数がつくことになります．都度但し書きを書くのは煩雑なので，積分の説明の間は「 $C$ は積分定数」という説明は添えないことにします．

{{< include problems/intro/09.qmd >}}

前の説で述べた定積分の値については，不定積分を用いて計算することができます．

::: {.Tbox data-latex="{定理}"}

$F(x)$ を $f(x)$ の不定積分とすると
$$\displaystyle\int_{a}^{b}f(x)\ dx=F(b)-F(a)$$
また，簡単のため $F(b)-F(a)$ のことを $\left[F(x)\right]_{a}^{b}$ とかく．

:::

ここで，不定積分は積分定数がついていたことを思い出します．実は上の計算をするときは，積分定数の値について考慮する必要はなく，好きなもの(通常は0でしょう)を使って問題ありません．なぜなら，$F(x)$ の代わりに $F(x)+C$ を使って右辺の計算をすると，引き算で結局 $C$ が消えてしまうからです．

::: {.Rbox data-latex="{例題}"}
次の定積分を求めよ．
$$\displaystyle\int_{0}^{8}x\ dx $$

:::

::: {.Abox data-latex="{解答}"}

$$\displaystyle\int_{}^{}x\ dx = \left[\displaystyle\frac{1}{2}x^2\right]_{0}^{8}=32-0=0$$

:::

