## 弾性力

今までは，運動方程式の $m\ddot{x}$ に注目した論理を展開してきました．では，実際に $F$ の部分に注目し始めましょう．

今までにすでに，抗力であったり摩擦力であったり，様々な力を見てきました．例題や問題では，重力や弾性力が出てきました．

これからはそのうちの一つである弾性力について見ていきましょう．

::: {.Tbox data-latex="{フックの法則}"}

理想的なばねにおいて，ばねの伸びはばねにかかる力に比例する．

$$
|F| = kx
$$

:::

ここで，$k$ はばね定数と呼ばれる定数で，ばねの硬さを表す量です．また，$x$ はばねの伸びを表す量で，ばねの自然長からの伸びを表します．

まだ数学・物理的に説明していないので，流し見程度で見ていただいて構わないのですが，フックの法則がこのような形になるのは，平衡点におけるポテンシャルの展開によって説明が可能です．

$$
U(x) = U(0) + \frac{1}{2}k(x-x_0)^2 + \cdots
$$

平衡点では，展開の際の一次の項が消えるため，二次の項が支配的になります．この二次の項がフックの法則を表すことになります．

では，実際の問題でどのようにフックの法則を使うのかを見ていきましょう．

\newpage

::: {.Rbox data-latex="{例題}"}

\begin{center}
\begin{tikzpicture}[>=Latex, thick]

  % 壁
  \draw[fill=gray!20] (-0.3,-1) rectangle (0,1);
  \draw[thick] (0,-1) -- (0,1);

  % バネ
  \draw[decorate, decoration={coil, segment length=4pt, amplitude=4pt}]
    (0,0) -- (3,0);

  % 質点
  \draw[fill=blue!10] (3,-0.5) rectangle (4.2,0.5);
  \node at (3.6,0) {$m$};

  % 床線
  \draw [->] (0,-0.5) -- (6.5,-0.5) node[right] {$x$};

  % 原点
  \draw (3.6,-0.5) node[below] {$0$};

\end{tikzpicture}
\end{center}

上図のように，壁にばねがついていて，ばねの先には質点 $m$ がついている．このとき，質点を右に $L$ だけ引っ張って離すと，どのような運動をするか．

:::

::: {.Abox data-latex="{解答}"}

運動方程式は次のようになる．

$$
m\ddot{x} = -kx
$$

:::

この運動方程式は，ばねの力が質点を原点に引き戻す向きで働いていることを表しています．つまり， $+$ 方向に引っ張ると， $-$ 方向に力が働き， $-$ 方向に引っ張ると， $+$ 方向に力が働きます．

では実際にこの運動方程式を解くにはどうすればいいのでしょうか．線形微分方程式の解法を知っている方はすぐに解けると思いますが，ここではもっと原始的な方法で解いてみましょう．

まず，非常に短い時間 $\tau$ を考えます．$x(t + \tau)$ は，非常に短い時間での変化なので，次のように近似できます．

$$
x(t + \tau) \approx x(t) + \dot{x}\qty(t + \frac{\tau}{2})\tau
$$

この式は， $t$ と $t + \tau$ の中点での速度を使って， $x(t + \tau)$ を近似する式です．

次に $\dot{x}\qty(t + \frac{\tau}{2})$ を近似します．この時間も非常に短いので，次のように近似できます．

$$
\dot{x}\qty(t + \frac{\tau}{2}) \approx \dot{x}\qty(t - \frac{\tau}{2}) + \ddot{x}(t)\tau
$$

これらの近似を駆使しながら，運動方程式を解いていきましょう．

まず，初期の状態です．簡単のために， $L = 1 \ \mathrm{m},\ k = 1 \ \mathrm{N m}^{-1},\ m = 1 \ \mathrm{kg}$ とします．つまり解くべき運動方程式は次のようになります．

$$
\ddot{x} = -x
$$

短い時間 $\tau$ は $0.1 \ \mathrm{s}$ として計算していきます．

$t = 0$ のとき， $x(0) = 1$ であり， $\ddot{x}(0) = -1$ です．ここで， $\dot{x}\qty(\frac{\tau}{2}) \approx \dot{x}(0) + \ddot{x}(0) \cdot \frac{\tau}{2} = -0.05$ と近似します．

次のステップです． $t = 0.1$ のとき， $x(0.1) \approx x(0) + \dot{x}\qty(0.5)\tau = 0.995$ となり， $\ddot{x}(0.1) = -0.995$ となります．ここで， $\dot{x}\qty(0.15) \approx \dot{x}\qty(0.05) + \ddot{x}(0.1) \cdot \frac{\tau}{2} = -0.14975$ と計算できます．

このようなステップを繰り返し，得られる値が以下の表です．

| $t$ | $x(t)$ | $\dot{x}(t)$ | $\ddot{x}(t)$ |
| --- | --- | --- | --- |
| 0.00 | 1.00000 | --- | -1.00000 |
| 0.05 | --- | -0.05000 | --- |
| 0.10 | 0.99500 | --- | -0.99500 |
| 0.15 | --- | -0.14950 | --- |
| 0.20 | 0.98005 | --- | -0.98005 |
| 0.25 | --- | -0.24751 | --- |
| 0.30 | 0.95530 | --- | -0.95530 |

ここまでは全ての値を計算しましたが，以降は $x(t)$ の値だけを出しておきます．

\newpage

| $t$ | $x(t)$ |
| --- | --- |
| 0.00 | 1.00000 |
| 0.10 | 0.99500 |
| 0.20 | 0.98005 |
| 0.30 | 0.95530 |
| 0.40 | 0.92100 |
| 0.50 | 0.87748 |
| 0.60 | 0.82519 |
| 0.70 | 0.76465 |
| 0.80 | 0.69647 |
| 0.90 | 0.62132 |
| 1.00 | 0.53995 |
| 1.10 | 0.45319 |
| 1.20 | 0.36189 |
| 1.30 | 0.26698 |
| 1.40 | 0.16939 |
| 1.50 | 0.07011 |
| 1.60 | -0.02987 |
| 1.70 | -0.12955 |
| 1.80 | -0.22793 |
| 1.90 | -0.32404 |
| 2.00 | -0.41691 |
| 2.10 | -0.50560 |
| 2.20 | -0.58924 |
| 2.30 | -0.66699 |
| 2.40 | -0.73807 |
| 2.50 | -0.80177 |
| 2.60 | -0.85745 |
| 2.70 | -0.90455 |
| 2.80 | -0.94261 |
| 2.90 | -0.97125 |

これをグラフにすると，以下のようになります．

```{=latex}
\begin{tikzpicture}
\begin{axis}[
    width=11cm,
    height=7cm,
    xlabel={$t$},
    ylabel={$x(t)$},
    xmin=0, xmax=3.0,
    ymin=-1.05, ymax=1.05,
    grid=both,
    minor tick num=1,
    thick
]
\addplot[
    blue,
    mark=*,
    mark size=1.2pt
] coordinates {
    (0.00, 1.00000)
    (0.10, 0.99500)
    (0.20, 0.98005)
    (0.30, 0.95530)
    (0.40, 0.92100)
    (0.50, 0.87748)
    (0.60, 0.82519)
    (0.70, 0.76465)
    (0.80, 0.69647)
    (0.90, 0.62132)
    (1.00, 0.53995)
    (1.10, 0.45319)
    (1.20, 0.36189)
    (1.30, 0.26698)
    (1.40, 0.16939)
    (1.50, 0.07011)
    (1.60, -0.02987)
    (1.70, -0.12955)
    (1.80, -0.22793)
    (1.90, -0.32404)
    (2.00, -0.41691)
    (2.10, -0.50560)
    (2.20, -0.58924)
    (2.30, -0.66699)
    (2.40, -0.73807)
    (2.50, -0.80177)
    (2.60, -0.85745)
    (2.70, -0.90455)
    (2.80, -0.94261)
    (2.90, -0.97125)
};
\end{axis}
\end{tikzpicture}
```

さて，このグラフ何かに似ていませんか？　そうです，このグラフは正弦波のような形をしています．実際，この運動方程式の解は次のようになります．

$$
x(t) = \sin t
$$

このような数値による近似的な解法は，数値解析の分野で非常に重要な手法の一つです．この方法はオイラー法と呼ばれています．

ですが，この微分方程式に関していえば，線形微分方程式という特別な種類の微分方程式であるため，解析的な解法が存在します．今のところその証明はさておき，とりあえずわかっているものとして解く方法を見ていきましょう．

$$
\dv[2]{x}{t} = -\omega^2 x
$$

この形の微分方程式の解は次のようになります．

$$
x(t) = A\sin(\omega t + \phi)
$$

ここで， $A$ は振幅と呼ばれる定数です． $\phi$ を含むこれらの定数は，初期条件によって決まります．

例えば先ほどの例題の初期条件を考えると， $x(0) = L$ であり， $\dot{x}(0) = 0$ であるため， $A = L$ であり， $\phi = 0$ となります．したがって，この場合の解は次のようになります．

$$
x(t) = L\sin(\sqrt{\frac{k}{m}} t)
$$

また，微分方程式の解は次のような形で書き下ろすこともできます．

$$
x(t) = A\sin(\omega t) + B\cos(\omega t)
$$

これは簡単な三角関数の和の形で書き下ろしたものです．この形の解も，初期条件によって定数 $A$ と $B$ が決まります．

ここで用語として， $\omega$ を角振動数と呼びます．振動の周期 $T = \frac{2\pi}{\omega}$ は，この振動が一周期を完了するのにかかる時間を表します．この振動の周波数 $f = \frac{1}{T} = \frac{\omega}{2\pi}$ は，この振動が一秒間に何回繰り返されるかを表します．

ここから言える簡単な事実として，

$$
\begin{aligned}
x &=  A\sin(\omega t + \phi) \\
v &= \dot{x} = A\omega \cos(\omega t + \phi)
\end{aligned}
$$

この式からわかるように，最大速度 $v_{\max} = A\omega$ となります．よく使われる関係なので，知っておきましょう．

次に，吊るされたばねの問題を考えてみましょう．

::: {.Rbox data-latex="{例題}"}

```{=latex}
\begin{wrapfigure}[3]{r}{0.2\linewidth}
\vspace{-1.0\baselineskip}
\centering
\resizebox{\linewidth}{!}{
\begin{tikzpicture}[>=Latex, thick]

  % パラメータ
  \def\topy{4}
  \def\massy{1.2}
  \def\wallleft{-1.2}
  \def\wallright{1.2}
  \def\massw{1.4}
  \def\massh{0.7}

  % 天井
  \draw[fill=gray!20] (\wallleft,\topy) rectangle (\wallright,\topy+0.3);
  \draw[thick] (\wallleft,\topy) -- (\wallright,\topy);

  % 固定端
  \fill (0,\topy) circle (2pt);

  % バネ
  \draw[decorate, decoration={coil, aspect=0.35, segment length=4pt, amplitude=4pt}]
    (0,\topy) -- (0,\massy+\massh/2);

  % 質点
  \draw[fill=blue!10] (-\massw/2,\massy-\massh/2) rectangle (\massw/2,\massy+\massh/2);
  \node at (0,\massy) {$m$};

  % 重力
  \draw[->] (0.9,\massy) -- (0.9,\massy-1.0) node[right] {$mg$};

  % 弾性力
  \draw[->] (-0.9,\massy) -- (-0.9,\massy+1.0) node[left] {$kx$};

  % x軸
  \draw[->] (1.3,\topy) -- (1.3,\massy+\massh)
    node[below] {$x$};

\end{tikzpicture}
}
\end{wrapfigure}
```

右図のように，天井からばねが吊るされていて，ばねの先には質点 $m$ がついている．バネは自然長のときに天井から $L$ だけ下がっている．自然長の時に手を離すと，バネはどのような運動をするか．

\vspace{4em}

:::

::: {.Abox data-latex="{解答}"}

この問題において， $x$ 軸は自然長の状態を原点として， $+$ 方向を下向きとする．このとき，運動方程式は次のようになる．

$$
\begin{aligned}
m\ddot{x} &= mg - kx \\
\ddot{x} &= -\frac{k}{m}\qty(x - \frac{mg}{k})
\end{aligned}
$$

ここで， $x - \frac{mg}{k}$ を新しい変数 $X$ と置くと，運動方程式は次のようになる．

$$
\ddot{X} = -\frac{k}{m}X
$$

この運動方程式の解は次のようになる．

$$
X(t) = A\sin\qty(\sqrt{\frac{k}{m}}t) + B\cos\qty(\sqrt{\frac{k}{m}}t)
$$

初期条件から， $t=0$ のとき， $X(0) = x(0) - \frac{mg}{k} = -\frac{mg}{k}$ であり， $\dot{X}(0) = 0$ であるため， $A = 0$ であり， $B = -\frac{mg}{k}$ となります．したがって，この場合の解は次のようになります．

$$
\begin{aligned}
X(t) &= -\frac{mg}{k}\cos\qty(\sqrt{\frac{k}{m}}t) \\
x(t) &= X(t) + \frac{mg}{k} \\
&= \frac{mg}{k}\qty(1 - \cos\qty(\sqrt{\frac{k}{m}}t)) \\
x - \frac{mg}{k} &= -\frac{mg}{k}\cos\qty(\sqrt{\frac{k}{m}}t)
\end{aligned}
$$

この解をグラフにすると，以下のようになる．

```{=latex}
\begin{center}
\begin{tikzpicture}
\begin{axis}[
    width=11cm,
    height=7cm,
    xlabel={$\sqrt{\frac{k}{m}}\,t$},
    y dir=reverse,
    ylabel={$X$},
    xmin=0, xmax=5*pi/2,
    ymin=-1.2, ymax=1.2,
    axis lines=left,
    axis x line = top,
    grid=both,
    minor tick num=1,
    domain=0:5*pi/2,
    samples=200,
    xtick={0,pi/2,pi,3*pi/2,2*pi,5*pi/2},
    xticklabels={$0$,$\frac{\pi}{2}$,$\pi$,$\frac{3\pi}{2}$,$2\pi$,$\frac{5\pi}{2}$},
    ytick={-1,0,1},
    yticklabels={$-\frac{mg}{k}$,$0$,$\frac{mg}{k}$}
]
\addplot[thick, blue] {-cos(deg(x))};
\addplot[dashed, red] {0};
\node[below right, red] at (axis cs:0.15,0) {$x = - \frac{mg}{k}$};
\end{axis}
\end{tikzpicture}
\end{center}

```

この振動の特徴としては，振動の中心が $x = -\frac{mg}{k}$ であり，振動の振幅が $\frac{mg}{k}$ であることが挙げられる．振動中心が釣り合いの位置であることに注意してください．

:::

このような振動は，単振動と呼ばれています．**単**振動と呼ばれている理由は，この振動が単純な正弦波の形をしているからです．現実にある振動は，複数の単振動を重ね合わせたものになっていることが多いため，その特徴を捉え，自在に扱えるようにすることはこれからの物理学において非常に重要なことになります．

\kenkyu 物理学の世界では，周期を持つような関数が登場することが多くあります．例えば，結晶内の電子の波動関数は周期的な関数になります．このような周期的な関数を扱うための数学的な道具として，フーリエ解析というものがあります．フーリエ解析は，周期的な関数を単振動の重ね合わせとして表す方法であり，物理学の様々な分野で非常に重要な役割を果たしています．

 