project: 
  title: "Working File"

format: 
  pdf:
    latex-engine: lualatex
    documentclass: ltjsbook
    classoption:
      - lualatex
      - ja=standard
      - b5paper
    fontsize: 11pt
    include-in-header: 
      - text: |
          % カスタムなスタイルファイルを読み込む
          \usepackage{sty/boxes}
          \usepackage{sty/anss}

          % 物理学の数式を簡単に書くためのパッケージ
          \usepackage{physics}

          \usepackage{tikz}
          \usetikzlibrary { decorations.pathmorphing, decorations.pathreplacing, decorations.shapes, }

          % すべての数式をディスプレイスタイルで表示する
          \everymath{\displaystyle}
          
                    
